In [1]:
import numpy as np
import sympy as sp
from sympy import Matrix, symbols
from IPython.display import Markdown

## Estados quânticos

- Estado "zero": |0⟩
- Estado "um": |1⟩

In [2]:
# Definir símbolos para clareza (como vetores coluna)
ket_0 = Matrix([[1], 
                [0]])
ket_1 = Matrix([[0], 
                [1]])

# Exibir de forma simbólica com LaTeX
display(Markdown(f"$ \\ket{{0}} = {sp.latex(ket_0)} $"))
display(Markdown(f"$ \\ket{{1}} = {sp.latex(ket_1)} $"))

$ \ket{0} = \left[\begin{matrix}1\\0\end{matrix}\right] $

$ \ket{1} = \left[\begin{matrix}0\\1\end{matrix}\right] $

In [3]:
# Uma outra maneira de definir os vetores usando NumPy
# Definindo os Qubits (Vetores de Estado)
# O estado |0>
q_zero = np.array([
    [1], 
    [0]
])

# O estado |1>
q_one = np.array([
    [0], 
    [1]
])

print("--- Estado Inicial ---")
print(f"Qubit Zero (|0>):\n{q_zero}")


--- Estado Inicial ---
Qubit Zero (|0>):
[[1]
 [0]]


Um qubit é representado como uma combinação linear
onde 𝛼 e 𝛽 são números complexos que satisfazem a
condição de normalização: |𝛼|² + |𝛽|² = 1.

Representação:

|ψ⟩ = 𝛼|0⟩ + 𝛽|1⟩

Assim:

$|ψ⟩ = 𝛼 * \begin{bmatrix} 1 \\ 0 \end{bmatrix} + 𝛽 * \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \begin{bmatrix} 𝛼 \\ 𝛽 \end{bmatrix}$

In [4]:
# Exemplo de uso: Um qubit é representado como uma combinação linear
# onde |ψ⟩ = α|0⟩ + β|1⟩, com α e β sendo números complexos

alpha, beta = symbols('alpha beta', complex=True)
psi = alpha * ket_0 + beta * ket_1

display(Markdown(f"$ \\ket{{\\psi}} = {sp.latex(psi)} $"))


$ \ket{\psi} = \left[\begin{matrix}\alpha\\\beta\end{matrix}\right] $

## Portas lógicas quânticas

- Porta X (NOT quântico): Inverte os estados |0⟩ e |1⟩.
- Porta H (Hadamard): Cria superposição dos estados |0⟩ e |1⟩.

### Porta X (NOT quântico)

A porta X, também conhecida como porta NOT quântica, é representada pela seguinte matriz:

$X = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$

Como funciona:

Aplica-se a porta X ao estado |0⟩:

$X|0⟩ = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} * \begin{bmatrix} 1 \\ 0 \end{bmatrix} = \begin{bmatrix} 0 \\ 1 \end{bmatrix} = |1⟩$

Aplica-se a porta X ao estado |1⟩:

$X|1⟩ = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} * \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} = |0⟩$

In [5]:
# Exemplo de aplicação da porta X (NOT quântico)

X = Matrix([[0, 1],
            [1, 0]])

# Aplicar a porta X ao estado |0⟩
result_0 = X * ket_0

display(Markdown(f"$ X \\ket{{0}} = {sp.latex(result_0)} $"))

# Aplicar a porta X ao estado |1⟩
result_1 = X * ket_1

display(Markdown(f"$ X \\ket{{1}} = {sp.latex(result_1)} $"))

$ X \ket{0} = \left[\begin{matrix}0\\1\end{matrix}\right] $

$ X \ket{1} = \left[\begin{matrix}1\\0\end{matrix}\right] $

In [6]:
# Uma outra maneira de definir as portas usando NumPy
# Definindo as Portas Lógicas (Matrizes Unitárias)

# Porta X (Pauli-X): Atua como um NOT clássico
# Matriz: [[0, 1], [1, 0]]
gate_x = np.array([
    [0, 1],
    [1, 0]
])


In [7]:

# --- 3. Executando Operações (Produto Escalar) ---

# APLICANDO A PORTA X em |0>
# Operação matemática: X * |0> = |1>
# Em Python (NumPy): np.dot(matriz, vetor)
novo_estado = np.dot(gate_x, q_zero)

print("\n--- Após aplicar a Porta X (NOT) ---")
print(f"Esperamos |1>, obtivemos:\n{novo_estado}")




--- Após aplicar a Porta X (NOT) ---
Esperamos |1>, obtivemos:
[[0]
 [1]]


### Porta H (Hadamard)

A porta H, ou porta Hadamard, é representada pela seguinte matriz:

$$H = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}$$

Como funciona:

Aplica-se a porta H ao estado |0⟩:

$$H|0⟩ = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \end{bmatrix} = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \cdot 1 + 1 \cdot 0 \\ 1 \cdot 1 + (-1) \cdot 0 \end{bmatrix} = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}$$

Agora, por que $\frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}$ vai ser igual a $\frac{1}{\sqrt{2}}|0⟩ + \frac{1}{\sqrt{2}}|1⟩$?

Isso ocorre porque o vetor $\begin{bmatrix} 1 \\ 1 \end{bmatrix}$ pode ser expresso como a soma dos vetores base:

$$\begin{bmatrix} 1 \\ 1 \end{bmatrix} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ 1 \end{bmatrix} = |0⟩ + |1⟩$$

Portanto:

$$\frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix} = \frac{1}{\sqrt{2}} (|0⟩ + |1⟩) = \frac{1}{\sqrt{2}}|0⟩ + \frac{1}{\sqrt{2}}|1⟩$$

Esta expressão demonstra o efeito fundamental da porta Hadamard: ela transforma um estado definido (|0⟩) em uma **superposição** com amplitudes iguais. Os coeficientes $\frac{1}{\sqrt{2}} \approx 0.707$ garantem a normalização, ou seja, $\left(\frac{1}{\sqrt{2}}\right)^2 + \left(\frac{1}{\sqrt{2}}\right)^2 = 1$.

Aplica-se a porta H ao estado |1⟩:

$$H|1⟩ = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix} \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \cdot 0 + 1 \cdot 1 \\ 1 \cdot 0 + (-1) \cdot 1 \end{bmatrix} = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix} = \frac{1}{\sqrt{2}}|0⟩ - \frac{1}{\sqrt{2}}|1⟩$$

Note que a porta Hadamard é **auto-adjunta** (igual à sua transposta conjugada), propriedade fundamental das portas quânticas reversíveis.

In [8]:
# Exemplo de aplicação da porta H (Hadamard)

# Definir a porta H
H = (1 / sp.sqrt(2)) * Matrix([[1, 1],
                               [1, -1]])

# Aplicar a porta H ao estado |0⟩
result_h0 = H * ket_0

# Aplicar a porta H ao estado |1⟩
result_h1 = H * ket_1

# Explicar o resultado

display(Markdown(f"$ H \\ket{{0}} = {sp.latex(H)} \\cdot {sp.latex(ket_0)} = {sp.latex(result_h0)} $"))

display(Markdown(f"$ {sp.latex(result_h0)} = \\frac{{1}}{{\\sqrt{{2}}}} \\ket{{0}} + \\frac{{1}}{{\\sqrt{{2}}}} \\ket{{1}} $"))

display(Markdown(f"$ H \\ket{{1}} = {sp.latex(H)} \\cdot {sp.latex(ket_1)} = {sp.latex(result_h1)} $"))

display(Markdown(f"$ {sp.latex(result_h1)} = \\frac{{1}}{{\\sqrt{{2}}}} \\ket{{0}} - \\frac{{1}}{{\\sqrt{{2}}}} \\ket{{1}} $"))

$ H \ket{0} = \left[\begin{matrix}\frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2}\\\frac{\sqrt{2}}{2} & - \frac{\sqrt{2}}{2}\end{matrix}\right] \cdot \left[\begin{matrix}1\\0\end{matrix}\right] = \left[\begin{matrix}\frac{\sqrt{2}}{2}\\\frac{\sqrt{2}}{2}\end{matrix}\right] $

$ \left[\begin{matrix}\frac{\sqrt{2}}{2}\\\frac{\sqrt{2}}{2}\end{matrix}\right] = \frac{1}{\sqrt{2}} \ket{0} + \frac{1}{\sqrt{2}} \ket{1} $

$ H \ket{1} = \left[\begin{matrix}\frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2}\\\frac{\sqrt{2}}{2} & - \frac{\sqrt{2}}{2}\end{matrix}\right] \cdot \left[\begin{matrix}0\\1\end{matrix}\right] = \left[\begin{matrix}\frac{\sqrt{2}}{2}\\- \frac{\sqrt{2}}{2}\end{matrix}\right] $

$ \left[\begin{matrix}\frac{\sqrt{2}}{2}\\- \frac{\sqrt{2}}{2}\end{matrix}\right] = \frac{1}{\sqrt{2}} \ket{0} - \frac{1}{\sqrt{2}} \ket{1} $

In [9]:
# Outra maneira de definir a porta H usando NumPy
# Porta H (Hadamard): Cria superposição
# Matriz: (1/√2) * [[1, 1], [1, -1]]
gate_h = (1 / np.sqrt(2)) * np.array([
    [1, 1],
    [1, -1]
])

# APLICANDO A PORTA HADAMARD em |0>
# Operação: H * |0> = Superposição
estado_superposicao = np.dot(gate_h, q_zero)

print("\n--- Após aplicar a Porta Hadamard (H) ---")
print(f"Estado de Superposição:\n{estado_superposicao}")
# Note que os valores são aprox 0.707 (que é 1/raiz(2))



--- Após aplicar a Porta Hadamard (H) ---
Estado de Superposição:
[[0.70710678]
 [0.70710678]]


**A Superposição**

Quando aplicamos a gate_h, o resultado foi: 

$$\begin{bmatrix} 0.707... \\ 0.707... \end{bmatrix}$$

Isso significa que o qubit não é nem 0 e nem 1. Ele contém "informação" de ambos. Matematicamente, ele é:

$$|\psi\rangle = 0.707|0\rangle + 0.707|1\rangle$$

### Produto interno (Inner Product) ou "bra-ket"

O produto interno entre dois estados quânticos |ψ⟩ e |φ⟩ é denotado por ⟨ψ|φ⟩ e é calculado como:

Ket é o vetor coluna que representa o estado quântico, enquanto bra é o vetor linha conjugado transposto correspondente.

> Como se calcula o vetor linha conjugado transposto?
> Para calcular o vetor linha conjugado transposto (bra) de um vetor coluna (ket), você deve seguir dois passos:
> 1. Transpor o vetor coluna, ou seja, transformar suas linhas em colunas.
> 2. Tomar o conjugado complexo de cada elemento do vetor transposto, o que significa substituir cada número complexo pelo seu conjugado (inverter o sinal da parte imaginária).

Se $|ψ⟩ = \begin{bmatrix} 𝛼 \\ 𝛽 \end{bmatrix}$ e $|φ⟩ = \begin{bmatrix} γ \\ δ \end{bmatrix}$, então:

$⟨ψ|φ⟩ = \begin{bmatrix} 𝛼 & 𝛽 \end{bmatrix} * \begin{bmatrix} γ \\ δ \end{bmatrix} = 𝛼*γ +𝛽*δ$

In [10]:
# Exemplo de produto interno

bra_0 = ket_0.T
bra_1 = ket_1.T

# ⟨0|0⟩
phi_00 = bra_0 * ket_0

# ⟨0|1⟩
phi_01 = bra_0 * ket_1

# ⟨1|0⟩
phi_10 = bra_1 * ket_0

# ⟨1|1⟩
phi_11 = bra_1 * ket_1

display(Markdown(f"$ \\langle 0 | 0 \\rangle = {sp.latex(bra_0)} * {sp.latex(ket_0)} = {phi_00[0,0]} $"))
display(Markdown(f"$ \\langle 0 | 1 \\rangle = {sp.latex(bra_0)} * {sp.latex(ket_1)} = {phi_01[0,0]} $"))
display(Markdown(f"$ \\langle 1 | 0 \\rangle = {sp.latex(bra_1)} * {sp.latex(ket_0)} = {phi_10[0,0]} $"))
display(Markdown(f"$ \\langle 1 | 1 \\rangle = {sp.latex(bra_1)} * {sp.latex(ket_1)} = {phi_11[0,0]} $"))

$ \langle 0 | 0 \rangle = \left[\begin{matrix}1 & 0\end{matrix}\right] * \left[\begin{matrix}1\\0\end{matrix}\right] = 1 $

$ \langle 0 | 1 \rangle = \left[\begin{matrix}1 & 0\end{matrix}\right] * \left[\begin{matrix}0\\1\end{matrix}\right] = 0 $

$ \langle 1 | 0 \rangle = \left[\begin{matrix}0 & 1\end{matrix}\right] * \left[\begin{matrix}1\\0\end{matrix}\right] = 0 $

$ \langle 1 | 1 \rangle = \left[\begin{matrix}0 & 1\end{matrix}\right] * \left[\begin{matrix}0\\1\end{matrix}\right] = 1 $

### Produto tensorial

O produto tensorial (ou produto de Kronecker) é uma operação matemática que combina dois estados quânticos para formar um estado composto. Se |ψ⟩ e |φ⟩ são dois estados quânticos, o produto tensorial é denotado por |ψ⟩ ⊗ |φ⟩.

Exemplo:


$$|0\rangle \otimes |0\rangle = \begin{bmatrix} 1 \\ 0 \end{bmatrix} \otimes \begin{bmatrix} 1 \\ 0 \end{bmatrix} = \begin{bmatrix} 1 \cdot \begin{bmatrix} 1 \\ 0 \end{bmatrix} \\ 0 \cdot \begin{bmatrix} 1 \\ 0 \end{bmatrix} \end{bmatrix} = \begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix}$$

In [11]:
# Exemplo de produto tensorial

# |0⟩ ⊗ |0⟩
tensor_00 = sp.kronecker_product(ket_0, ket_0)
display(
    Markdown(
        f"$$\\ket{{0}} \\otimes \\ket{{0}} = {sp.latex(ket_0)} \\otimes {sp.latex(ket_0)} = \\begin{{bmatrix}} 1 \\cdot {sp.latex(ket_0)} \\\\ 0 \\cdot {sp.latex(ket_0)} \\end{{bmatrix}} = {sp.latex(tensor_00)} = \\ket{{00}}$$"
    )
)

# |0⟩ ⊗ |1⟩
tensor_01 = sp.kronecker_product(ket_0, ket_1)
display(
    Markdown(
        f"$$\\ket{{0}} \\otimes \\ket{{1}} = {sp.latex(ket_0)} \\otimes {sp.latex(ket_1)} = \\begin{{bmatrix}} 1 \\cdot {sp.latex(ket_1)} \\\\ 0 \\cdot {sp.latex(ket_1)} \\end{{bmatrix}} = {sp.latex(tensor_01)} = \\ket{{01}}$$"
    )
)

# |1⟩ ⊗ |0⟩
tensor_10 = sp.kronecker_product(ket_1, ket_0)
display(
    Markdown(
        f"$$\\ket{{1}} \\otimes \\ket{{0}} = {sp.latex(ket_1)} \\otimes {sp.latex(ket_0)} = \\begin{{bmatrix}} 0 \\cdot {sp.latex(ket_0)} \\\\ 1 \\cdot {sp.latex(ket_0)} \\end{{bmatrix}} = {sp.latex(tensor_10)} = \\ket{{10}}$$"
    )
)

# |1⟩ ⊗ |1⟩
tensor_11 = sp.kronecker_product(ket_1, ket_1)
display(
    Markdown(
        f"$$\\ket{{1}} \\otimes \\ket{{1}} = {sp.latex(ket_1)} \\otimes {sp.latex(ket_1)} = \\begin{{bmatrix}} 0 \\cdot {sp.latex(ket_1)} \\\\ 1 \\cdot {sp.latex(ket_1)} \\end{{bmatrix}} = {sp.latex(tensor_11)} = \\ket{{11}}$$"
    )
)

$$\ket{0} \otimes \ket{0} = \left[\begin{matrix}1\\0\end{matrix}\right] \otimes \left[\begin{matrix}1\\0\end{matrix}\right] = \begin{bmatrix} 1 \cdot \left[\begin{matrix}1\\0\end{matrix}\right] \\ 0 \cdot \left[\begin{matrix}1\\0\end{matrix}\right] \end{bmatrix} = \left[\begin{matrix}1\\0\\0\\0\end{matrix}\right] = \ket{00}$$

$$\ket{0} \otimes \ket{1} = \left[\begin{matrix}1\\0\end{matrix}\right] \otimes \left[\begin{matrix}0\\1\end{matrix}\right] = \begin{bmatrix} 1 \cdot \left[\begin{matrix}0\\1\end{matrix}\right] \\ 0 \cdot \left[\begin{matrix}0\\1\end{matrix}\right] \end{bmatrix} = \left[\begin{matrix}0\\1\\0\\0\end{matrix}\right] = \ket{01}$$

$$\ket{1} \otimes \ket{0} = \left[\begin{matrix}0\\1\end{matrix}\right] \otimes \left[\begin{matrix}1\\0\end{matrix}\right] = \begin{bmatrix} 0 \cdot \left[\begin{matrix}1\\0\end{matrix}\right] \\ 1 \cdot \left[\begin{matrix}1\\0\end{matrix}\right] \end{bmatrix} = \left[\begin{matrix}0\\0\\1\\0\end{matrix}\right] = \ket{10}$$

$$\ket{1} \otimes \ket{1} = \left[\begin{matrix}0\\1\end{matrix}\right] \otimes \left[\begin{matrix}0\\1\end{matrix}\right] = \begin{bmatrix} 0 \cdot \left[\begin{matrix}0\\1\end{matrix}\right] \\ 1 \cdot \left[\begin{matrix}0\\1\end{matrix}\right] \end{bmatrix} = \left[\begin{matrix}0\\0\\0\\1\end{matrix}\right] = \ket{11}$$

## Representação de dois qubits

- Estado |00⟩: $\begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix}$
- Estado |01⟩: $\begin{bmatrix} 0 \\ 1 \\ 0 \\ 0 \end{bmatrix}$
- Estado |10⟩: $\begin{bmatrix} 0 \\ 0 \\ 1 \\ 0 \end{bmatrix}$
- Estado |11⟩: $\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}$

Dois qubits podem estar em superposição de todos os quatro estados possíveis:

$$|\psi\rangle = 𝛼|00\rangle + 𝛽|01\rangle + γ|10\rangle + δ|11\rangle$$
onde |𝛼|² + |𝛽|² + |γ|² + |δ|² = 1.



### Porta Controlled NOT (CNOT)

A porta CNOT (Controlled NOT) é uma porta lógica quântica que atua em dois qubits: um qubit de controle e um qubit alvo. A operação da porta CNOT é a seguinte:

- Se o qubit de controle estiver em |0⟩, o qubit alvo permanece inalterado.
- Se o qubit de controle estiver em |1⟩, o qubit alvo é invertido (0 vira 1 e 1 vira 0).

A porta CNOT é representada pela seguinte matriz:

$$\text{CNOT} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix}$$

Quando aplicamos a porta CNOT a um estado composto de dois qubits, o resultado depende do estado do qubit de controle. Por exemplo, se aplicarmos a porta CNOT ao estado |10⟩ (onde o primeiro qubit é o controle e o segundo é o alvo), o resultado será |11⟩, pois o qubit de controle está em |1⟩, então o qubit alvo é invertido.

Por exemplo:

$$\text{CNOT}|11⟩ = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{bmatrix} * \begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 1 \\ 0 \end{bmatrix} = |10⟩$$


In [12]:
# Implementação do uso da porta CNOT

# Definindo a porta CNOT
CNOT = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])  

# |11> 

q_11 = np.array([
    [0],
    [0],
    [0],
    [1]
])

# Aplicando a porta CNOT em |11>
novo_estado_cnot = np.dot(CNOT, q_11)
print("\n--- Após aplicar a Porta CNOT em |11> ---")
print(f"Esperamos |10>, obtivemos:\n{novo_estado_cnot}")

# Aplicando a porta CNOT em |10>
q_10 = np.array([
    [0],
    [0],
    [1],
    [0]
])

novo_estado_cnot_10 = np.dot(CNOT, q_10)
print("\n--- Após aplicar a Porta CNOT em |10> ---")
print(f"Esperamos |11>, obtivemos:\n{novo_estado_cnot_10}")






--- Após aplicar a Porta CNOT em |11> ---
Esperamos |10>, obtivemos:
[[0]
 [0]
 [1]
 [0]]

--- Após aplicar a Porta CNOT em |10> ---
Esperamos |11>, obtivemos:
[[0]
 [0]
 [0]
 [1]]


## O Colapso (Probabilidade)
 
Ao final, calculamos o quadrado desses números (0.707² ≈ 0.5). Isso diz ao computador: "Jogue uma moeda. Tem 50% de chance de dar Cara (0) e 50% de dar Coroa (1)". É aqui que a computação quântica deixa de ser determinística (como a clássica) e passa a ser probabilística.

In [13]:

# A Medição (O Colapso)
# Na teoria: A probabilidade de medir 0 ou 1 é o quadrado da amplitude (módulo ao quadrado).

def medir_qubit(estado_vetor):
    # Extrair amplitudes (alpha e beta)
    alpha = estado_vetor[0][0]
    beta = estado_vetor[1][0]
    
    # Calcular probabilidades (Born Rule): |amplitude|^2
    prob_0 = abs(alpha) ** 2
    prob_1 = abs(beta) ** 2
    
    print(f"\nProbabilidade calculada de ser 0: {prob_0:.2f}")
    print(f"Probabilidade calculada de ser 1: {prob_1:.2f}")
    
    # Simular o "lance de dados" da natureza
    resultado = np.random.choice([0, 1], p=[prob_0, prob_1])
    return resultado

# Vamos medir nosso estado de superposição
leitura = medir_qubit(estado_superposicao)
print(f"Resultado da Medição (Colapso): |{leitura}>")


Probabilidade calculada de ser 0: 0.50
Probabilidade calculada de ser 1: 0.50
Resultado da Medição (Colapso): |1>


Por que não usar apenas NumPy sempre? Se é tão simples, por que precisamos do Qiskit ou PennyLane?

Porque as matrizes crescem exponencialmente.

- 1 Qubit = Matriz $2 \times 2$
- 2 Qubits = Matriz $4 \times 4$
- 3 Qubits = Matriz $8 \times 8$
- ...
- 50 Qubits = Matriz $1.125.899.906.842.624 \times 1.125.899.906.842.624$
  
O seu computador não tem memória RAM suficiente para armazenar a matriz de 50 qubits usando NumPy. Os frameworks como Qiskit usam truques matemáticos e otimizações (ou enviam para computadores reais) para lidar com essa complexidade.